### ISSUE TITLE
ImageMagic 升级后，图形验证码报错， 最新版的 rucaptcha 也不起作用

### ISSUE THREAD

**Issue by xiajian** [huacnlee/rucaptcha#25]
```
RuntimeError (RuCaptcha: convert: not authorized `-' @ error/constitute.c/ReadImage/453.
convert: missing an image filename `png:-' @ error/convert.c/ConvertImageCommand/3015.):
  rucaptcha (0.4.5) lib/rucaptcha/captcha.rb:81:in `create'
  rucaptcha (0.4.5) lib/rucaptcha/cache.rb:18:in `block in create_with_cache'
  activesupport (4.2.5) lib/active_support/cache.rb:299:in `block in fetch'
  activesupport (4.2.5) lib/active_support/cache.rb:585:in `block in save_block_result_to_cache'
  activesupport (4.2.5) lib/active_support/cache.rb:547:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:166:in `instrument'
  activesupport (4.2.5) lib/active_support/cache.rb:547:in `instrument'
  activesupport (4.2.5) lib/active_support/cache.rb:584:in `save_block_result_to_cache'
  activesupport (4.2.5) lib/active_support/cache.rb:299:in `fetch'
  rucaptcha (0.4.5) lib/rucaptcha/cache.rb:17:in `create_with_cache'
  rucaptcha (0.4.5) lib/rucaptcha/controller_helpers.rb:13:in `generate_rucaptcha'
  rucaptcha (0.4.5) app/controllers/ru_captcha/captcha_controller.rb:10:in `index'
  actionpack (4.2.5) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.5) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.5) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.5) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
  activesupport (4.2.5) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
  activesupport (4.2.5) lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
  marginalia (1.3.0) lib/marginalia.rb:77:in `record_query_comment'
  activesupport (4.2.5) lib/active_support/callbacks.rb:432:in `block in make_lambda'
  activesupport (4.2.5) lib/active_support/callbacks.rb:312:in `block in halting'
  activesupport (4.2.5) lib/active_support/callbacks.rb:497:in `block in around'
  activesupport (4.2.5) lib/active_support/callbacks.rb:505:in `call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:92:in `__run_callbacks__'
  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.5) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.5) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.5) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.5) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.5) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.5) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.5) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.5) lib/action_controller/metal.rb:196:in `dispatch'
  actionpack (4.2.5) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.5) lib/action_controller/metal.rb:237:in `block in action'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:45:in `serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:817:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.5) lib/rails/railtie.rb:194:in `method_missing'
  actionpack (4.2.5) lib/action_dispatch/routing/mapper.rb:51:in `serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `each'
  actionpack (4.2.5) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.5) lib/action_dispatch/routing/route_set.rb:817:in `call'
  oneapm_rpm (1.3.6) lib/one_apm/rack/middleware_hooks.rb:13:in `traced_call'
  oneapm_rpm (1.3.6) lib/one_apm/rack/middleware_tracing.rb:65:in `call'
  oneapm_rpm (1.3.6) lib/one_apm/rack/browser_monitoring.rb:19:in `traced_call'
  oneapm_rpm (1.3.6) lib/one_apm/rack/middleware_tracing.rb:65:in `call'
  warden (1.2.6) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.6) lib/warden/manager.rb:34:in `catch'
  warden (1.2.6) lib/warden/manager.rb:34:in `call'
  rack (1.6.4) lib/rack/etag.rb:24:in `call'
  rack (1.6.4) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.4) lib/rack/head.rb:13:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.4) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.4) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.5) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.5) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.5) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
  activesupport (4.2.5) lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
  activesupport (4.2.5) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.5) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  airbrake (4.0.0) lib/airbrake/rails/middleware.rb:13:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in `call'
  airbrake (4.0.0) lib/airbrake/user_informer.rb:16:in `_call'
  airbrake (4.0.0) lib/airbrake/user_informer.rb:12:in `call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/application.rb:165:in `call'
  oneapm_rpm (1.3.6) lib/one_apm/rack/middleware_tracing.rb:65:in `call'
  puma (2.9.0) lib/puma/configuration.rb:71:in `call'
  puma (2.9.0) lib/puma/server.rb:490:in `handle_request'
  puma (2.9.0) lib/puma/server.rb:361:in `process_client'
  puma (2.9.0) lib/puma/server.rb:254:in `block in run'
  puma (2.9.0) lib/puma/thread_pool.rb:92:in `block in spawn_thread'
```

imagemagick 的 convert 命令的版本: 

```
Version: ImageMagick 6.7.2-7 2016-05-09 Q16 http://www.imagemagick.org
Copyright: Copyright (C) 1999-2011 ImageMagick Studio LLC
Features: OpenMP
```

**Comment by huacnlee** [comment]
ImageMagick 6.9

**Comment by xiajian** [comment]
6.7.2-7 中 之前用的版本，也是可以的。升级了一下小版本后，就不行了。

**Comment by qx** [comment]
centos7 安装问题
默认安装里面少一个delegate,叫freetype
http://www.imagemagick.org/download/delegates/  先编译freetype,再编译ImageMagick

完整安装
wget http://www.imagemagick.org/download/...2-6.x86_64.rpm
rpm -Uvh ImageMagick-6.9.2-6.x86.rpm#这一步可能需要各种dependence, 最要不要这样安装,直接编译


yum install ghostscript-fonts 
cd /usr/local/src 
wget http://www.imagemagick.org/download/ImageMagick.tar.gz tar xvzf ImageMagick.tar.gz 
##这一步要加入freetype支持,再编译,否则你还得再弄一次
http://www.imagemagick.org/download/delegates/freetype-2.6.2.tar.gz
tar xzvf freetype-2.6.2.tar.gz
cd freetype-2.6.2
./configure && make

cd ImageMagick-7.0.1-10 
./configure && make

make install

折腾一个多小时安装,蛋疼,@huancnlee 希望补充到centos的安装readme

**Comment by xiajian** [comment]
其实，可以使用 centos 的第三方的 Remi 库，省的自己编译安装：

```
wget http://dl.fedoraproject.org/pub/epel/6/x86_64/epel-release-6-8.noarch.rpm
rpm -Uvh epel-release-6*.rpm

wget http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
rpm -Uvh remi-release-6*.rpm

yum remove ImageMagick  ImageMagick-devel

# 注意修改，/etc/yum.repos.d/remi.repo ， 将 remi 段的 enabled=0 修改为 enabled=1

yum install ImageMagick-last.x86_64 ImageMagick-last-devel.x86_64 # 最新安装的 6.9.xx
```

哎，我我折腾了小半天，才解决这个在 centos 6.5 上遇到的坑爹的问题。

参考： https://www.vultr.com/docs/install-imagemagick-on-centos-6

**Comment by huacnlee** [comment]
用 2.0.0 版本，不再需要 ImageMagick 了
