### ISSUE TITLE
Windows上的rucaptcha image并没有出现

### ISSUE THREAD

**Issue by zhangkun** [huacnlee/rucaptcha#45]
1. 配置是 self.cache_store = :redis_store

    有关的gem：
```
    gem 'rucaptcha', '~> 2.1.2'
    gem 'redis-rails'
```

2. 报错信息是

```
Started GET "/rucaptcha/" for 127.0.0.1 at 2017-03-22 14:42:25 +0800
Processing by RuCaptcha::CaptchaController#index as HTML
Sent file GIF89a一堆乱码(0.0ms)
Completed 500 Internal Server Error in 2833ms (ActiveRecord: 1.0ms)

ArgumentError (string contains null byte):
actionpack (5.0.2) lib/action_controller/metal/data_streaming.rb:67:in `file?'
actionpack (5.0.2) lib/action_controller/metal/data_streaming.rb:67:in `send_file'
```

调试后发现 gems/rucaptcha-2.1.2/app/controllers/ru_captcha/captcha_controller.rb
```
if Gem.win_platform?
  send_file data, opts
else
  send_data data, opts
end
```
如果是windows时，使用的send_file，修改为send_data就会正常显示图片了

**Comment by huacnlee** [comment]
Thanks! 

Fixed in version 2.1.3

**Comment by zhangkun** [comment]
Thank you very much !

2017-03-22 15:53 GMT+08:00 Jason Lee <notifications@github.com>:
